apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: 097391169945.dkr.ecr.ap-northeast-2.amazonaws.com/demo-frontend
  newName: 097391169945.dkr.ecr.ap-northeast-2.amazonaws.com/demo-frontend
  newTag: 0a6033ab
resources:
- ../../base
patchesStrategicMerge:
- front-deployment-patch.yaml
- front-service-patch.yaml
